algorithm:
  image: registry.desenvpln.com.br/planning-algorithm:latest
  ports:
  - 7776
  - 9990
  environment:
  - PLANNIG
  - PLANNING_DB_TYPE=${PLANNING_DB_TYPE}
  - PLANNING_DB_HOSTNAME=${PLANNING_DB_HOSTNAME}
  - PLANNING_DB_DATABASE=${PLANNING_DB_DATABASE}
  - PLANNING_DB_PORT=${PLANNING_DB_PORT}
  - PLANNING_DB_USERNAME=${PLANNING_DB_USERNAME}
  - PLANNING_DB_PASSWORD=${PLANNING_DB_PASSWORD}
  - PLANNING_DB_JNDI=${PLANNING_DB_JNDI}
  - PLANNING_STACK=true
web:
  image: registry.desenvpln.com.br/planning-web:latest
  ports:
  - 7776
  - 9990
  links:
  - algorithm
  environment:
  - PLANNING_DB_TYPE=${PLANNING_DB_TYPE}
  - PLANNING_DB_HOSTNAME=${PLANNING_DB_HOSTNAME}
  - PLANNING_DB_DATABASE=${PLANNING_DB_DATABASE}
  - PLANNING_DB_PORT=${PLANNING_DB_PORT}
  - PLANNING_DB_USERNAME=${PLANNING_DB_USERNAME}
  - PLANNING_DB_PASSWORD=${PLANNING_DB_PASSWORD}
  - PLANNING_DB_JNDI=${PLANNING_DB_JNDI}
  - PLANNING_STACK=true
